name: Create Release

on:
  push:
    branches:
      - main  # 릴리즈를 생성할 브랜치

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run jest
      run: npm run jest  # 테스트 명령어는 프로젝트에 따라 다를 수 있습니다.

  release:
    needs: build  # 빌드 작업이 성공해야 실행됩니다.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write 
    steps:
    - name: Extract branch or tag name
      id: extract_ref
      run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF#refs/*/})"
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
